### ISSUE TITLE
Spotify Bad user name or password Docker

### ISSUE THREAD

**Issue by mietzen** [tizonia/tizonia-openmax-il#558] opened 2019-02-12 07:14 UTC
### Description
I can't login with the user and password working in the normal spotify app.

```
docker-tizonia --spotify-playlist-id https://open.spotify.com/playlist/37i9dQZF1DWVCHIm2MEeIy --spotify-user XXXX --spotify-password XXXX

[Spotify] [FATAL] Login attempt failed. Bad user name or password.
tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.spotify.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```

### Steps to Reproduce

Try to login

**Expected behavior:** [What you expect to happen]
Login works

**Actual behaviour:** [What actually happens]
Login doesn't work

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

```
uname -a
Linux fedora 4.20.6-200.fc29.x86_64 #1 SMP Thu Jan 31 15:50:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
docker --version
Docker version 1.13.1, build 55f9e52-unsupported
```

```
docker-tizonia --version              
tizonia 0.17.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>
```

### Installation Method Used
Docker

### Additional Information

> docker-tizonia --youtube-audio-mix-search "Queen Official" 

works

**Comment by tizonia** [comment] 2019-02-24 22:48
Hi!, thanks for taking the time to report this issue.

Is your Spotify account associated to your Facebook? Tizonia works out-of-the-box with non-Facebook Spotify accounts. However, if you have a Facebook login, you might still be able to use Tizonia by obtaining a 'device password' or an 'app-specific password'.

I recommend reading the 'Dependencies' section in this README file:
https://github.com/mopidy/mopidy-spotify/blob/develop/README.rst

**Comment by mietzen** [comment] 2019-02-25 13:27
No I don't have FB


Tizonia <http://notifications@github.com > hat am February 24, 2019 um 11:48 PM geschrieben:

**Comment by tizonia** [comment] 2019-02-25 21:35
OK,

Are you inserting in `--spotify-user XXXX` the 

> Username

 displayed in your profile?
https://www.spotify.com/uk/account/overview/

![screenshot from 2019-02-25 21-31-02](https://user-images.githubusercontent.com/3161606/53370220-1509c800-3945-11e9-9524-27f72feca717.png)

**Comment by mietzen** [comment] 2019-02-26 18:39
Yes, I tried via comandline and config File 


Tizonia <http://notifications@github.com > hat am February 25, 2019 um 10:35 PM geschrieben:

**Comment by tizonia** [comment] 2019-03-10 19:53
@mietzen 

Are there any special characters in your password? Another user has problems is $ and # characters:
See https://github.com/tizonia/tizonia-openmax-il/issues/571#issuecomment-471337354

**Comment by mietzen** [comment] 2019-03-11 16:19
Yes it has a $ in it :-D

**Comment by tizonia** [comment] 2019-03-11 20:28
I see, does it have any other special chars? If the answer is no, I will close this issue and mark as a duplicate of #571.

**Comment by mietzen** [comment] 2019-03-11 20:30
You may close this one 👍

**Comment by tizonia** [comment] 2019-03-11 21:17
Closing as duplicate of #571

**Closed by tizonia** 2019-03-11 21:17 UTC
Labels: duplicate
