### ISSUE TITLE
spotify credentials in ~/.config/tizonia/tizonia.conf issue

### ISSUE THREAD

**Issue by liquidxd** [tizonia/tizonia-openmax-il#545] opened 2019-01-07 23:05 UTC
hi
I'm having an issue in debian stretch tizonia 0.16.0. Provide spotify credentials in ~/.config/tizonia/tizonia.conf
but when i run tizonia --spotify-playlist "playlist" show me "Need to provide a Spotify user name.
" . Thanks

**Comment by juanrubio** [comment] 2019-01-07 23:34
Hi!, thanks for taking the time to report an issue.

Please note that the configuration file is located in a different directory if you have installed Tizonia from the Snap package. This is a pretty common source of confusion. See:
https://github.com/tizonia/tizonia-openmax-il#configuration

Having said that, please note that even if you provide your Spotify credentials correctly, there is currently an issue that prevents Spotify logins using Tizonia. See https://github.com/tizonia/tizonia-openmax-il/issues/531 for the details. The issue is currently being worked on.

**Comment by tizonia** [comment] 2019-01-08 14:56
@liquidxd 

I'm closing this issue now since configuration values are being read correctly in both Snap and deb installations. Please add any comments here if you still are experiencing issues.

**Closed by tizonia** 2019-01-08 14:56 UTC
