### ISSUE TITLE
Tizonia plays a Spotify album incorrectly. It plays track 1 and last track only. 

### ISSUE THREAD

**Issue by banoslo** [tizonia/tizonia-openmax-il#564] opened 2019-02-23 00:14 UTC
### Description

Tizonia plays a Spotify album incorrectly. It plays track 1 and after it the last track. (On a raspberry 3)

### Steps to Reproduce
0. Install tizonia on a raspberry pi 3
1. Start tizonia with spotify album id: 3iWNsrEs9D0FFlKFfscdvL
2. Wait until the end of the first track

**Expected behavior:**
Track 2 will be played after track 1

**Actual behaviour:**
Last track will be played after track 1

**Reproduces how often:**
100%

### Versions
0.17.0 on the latest raspbian

Debug Info:
	    * [Boost 1_62]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v0.7.91]

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Use the information obtained from `tizonia --version` and `tizonia
--debug`. Also, please include the OS details and what version you are running
(e.g. `cat /etc/os-release`).

### Installation Method Used

Install procedure from your webpage. 

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by tizonia** [comment] 2019-02-24 20:28
H!, thanks for reporting this issue.

I'm going to close it as a duplicate of #560. The description is slightly different, but both talk about the same problem. Please follow the progress on #560, a fix will be provided there.

**Closed by tizonia** 2019-02-24 20:28 UTC
