### ISSUE TITLE
Tizonia stuck after successfully loading spotify songs

### ISSUE THREAD

**Issue by siulynot** [tizonia/tizonia-openmax-il#567] opened 2019-02-28 12:40 UTC
### Description

I execute tizonia like this: `tizonia --spotify-artist "Wet Baes" --spotify-user XXXXXXXX --spotify-password XXXXXXXXX --shuffle`

Everything seems to load fine, only that player never starts.

### Steps to Reproduce

1. Execute tizonia command: `
tizonia --spotify-artist "Wet Baes" --spotify-user XXXXXXXX --spotify-password XXXXXXXXX --shuffle
`
2. 
```
tizonia 0.17.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Spotify] [Connecting] : '129962567'.
[Spotify] [Artist search] 'Wet Baes'.
[Spotify] [Artist] 'Wet Baes'.
[Spotify] [Artist top tracks] 'Wet Baes'.
[Spotify] [Track] 'Dancing in the Dark' [Wet Baes].
[Spotify] [Track] 'Midnight Caller' [Wet Baes].
[Spotify] [Track] 'Guess' [Wet Baes].
[Spotify] [Track] 'Goodbye' [Wet Baes].
[Spotify] [Track] 'Changes' [Wet Baes].
[Spotify] [Track] 'Is This Really Happening?' [Wet Baes].
[Spotify] [Track] 'Secret (Love Song)' [Wet Baes].
[Spotify] [Track] 'Girl' [Wet Baes].
[Spotify] [Track] 'All Night' [Wet Baes].
[Spotify] [Track] 'Midnight Caller - RELAYER Remix' [Wet Baes].
[Spotify] [Album] 'Changes'.
[Spotify] [Track] 'Overture' [Wet Baes].
[Spotify] [Track] 'Changes' [Wet Baes].
[Spotify] [Track] 'Secret (Love Song)' [Wet Baes].
[Spotify] [Track] 'Is This Really Happening?' [Wet Baes].
[Spotify] [Track] 'Feels / Dancing in the Dark (Reprise)' [Wet Baes].
[Spotify] [Track] 'Guess' [Wet Baes].
[Spotify] [Track] 'Stay' [Wet Baes].
[Spotify] [Track] 'The End (Sitting in the Sun)' [Wet Baes].
[Spotify] [Album] 'Secret (Love Song)'.
[Spotify] [Track] 'Secret (Love Song)' [Wet Baes].
[Spotify] [Album] 'Changes'.
[Spotify] [Track] 'Changes' [Wet Baes].
[Spotify] [Album] 'Midnight Caller (RELAYER Remix)'.
[Spotify] [Track] 'Midnight Caller - RELAYER Remix' [Wet Baes].
[Spotify] [Album] 'Dancing in the Dark'.
[Spotify] [Track] 'Dancing in the Dark' [Wet Baes].
[Spotify] [Album] 'Youth Attraction'.
[Spotify] [Track] 'Intro' [Wet Baes].
[Spotify] [Track] 'All Night' [Wet Baes].
[Spotify] [Track] 'Goodbye' [Wet Baes].
[Spotify] [Track] 'Midnight Caller' [Wet Baes].
[Spotify] [Track] 'Girl' [Wet Baes].
[Spotify] [Album] 'No Science EP'.
[Spotify] [Track] 'Don't Be Mad (feat. Elebleu)' [Noa Sainz].
[Spotify] [Track] 'FYT' [Noa Sainz].
[Spotify] [Track] 'Freedom' [Noa Sainz].
[Spotify] [Track] 'Yo No Soy' [Noa Sainz].
[Spotify] [Track] 'Amadis (feat. Wet Baes)' [Noa Sainz].
[Spotify] [Track] 'Siempre' [Noa Sainz].
[Spotify] [Album] 'Dónde Estabas (Azul) [Remixes]'.
[Spotify] [Track] 'Donde Estabas (Azul) - Dr. Zupreeme Remix' [Hello Seahorse!].
[Spotify] [Track] 'Donde Estabas (Azul) - Eviltapes Remix' [Hello Seahorse!].
[Spotify] [Track] 'Donde Estabas (Azul) - Ghetto Kids Remix' [Hello Seahorse!].
[Spotify] [Track] 'Donde Estabas (Azul) - Wet Baes Remix' [Hello Seahorse!].
[Spotify] [Tracks in queue] '37'.
[Spotify] [Cache]: '/var/tmp/tizonia-siu-spotify-129962567'
[Spotify] [Login] '129962567' logged in.
```

3. Everything seems to load fine without issues, but player never starts playing. I had this working perfectly on this computer (Xubuntu 18.04) but after installing zsh, it seems to have stopped working.

**Expected behavior:** I expect the player to start playing music

**Actual behaviour:** It gets stuck after logging in and loading tracks

**Reproduces how often:** Every time

### Versions
```
 tizonia --version
tizonia 0.17.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>
```
```
Debug Info:
	    * [Boost 1_58]
	    * [TagLib 1.9.1]
	    * [MediaInfoLib - v17.12]
```

``` 
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

```

### Installation Method Used

`curl -kL https://goo.gl/Vu8qGR | bash`

### Additional Information

I recently installed zsh and oh-my-zsh, although i try to execute tizonia in bash with the same results. Those are the only recent changes made to the system.

**Comment by juanrubio** [comment] 2019-02-28 19:01
Hi!, thanks for taking the time to report an issue.

The same search works fine on my system.

One thing that looks odd is that your system seems to have some really old version of certain packages. For example, this is what I get on my Ubuntu 18.04.2 install:

```
➜  ~  tizonia --debug                                                             
tizonia 0.17.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_65_1]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v17.12]
```

but you are getting:

> 	    * [Boost 1_58]
> 	    * [TagLib 1.9.1]

These Boost and TagLib versions are from Xenial, not Bionic:
- https://packages.ubuntu.com/xenial/libboost-all-dev
- https://packages.ubuntu.com/xenial/taglib

Would you be able to upload here the output of `cat /etc/*-release`?. This is what I get:

```
➜  ~  cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by siulynot** [comment] 2019-02-28 19:51
Thanks for the fast reply, 

This system indeed is a Xenial to Bionic upgrade, so it might have old packages hanging around. Let me try to get the newer packages and test. 

Will update when i do.

Thanks.

**Comment by siulynot** [comment] 2019-02-28 22:33
So i verified and libboost was already 1.65 on my system. Also there is no package available for Taglib, but i followed the command to purge tizonia and deleted the binaries from /usr/bin/

Now i tried to install tizonia from scratch and i get an error: 

```
curl -kL https://goo.gl/Vu8qGR | bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100   150  100   150    0     0     12      0  0:00:12  0:00:11  0:00:01    34
100  4706  100  4706    0     0    266      0  0:00:17  0:00:17 --:--:--  1096
DISTRIB_CODENAME=bionic
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
libxslt1-dev is already the newest version (1.1.29-5).
python-dev is already the newest version (2.7.15~rc1-1).
curl is already the newest version (7.58.0-2ubuntu3.6).
git is already the newest version (1:2.17.1-1ubuntu0.4).
libssl-dev is already the newest version (1.1.0g-2ubuntu4.3).
libxml2-dev is already the newest version (2.9.4+dfsg1-6.1ubuntu1.2).
apt-transport-https is already the newest version (1.6.8).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Hit:2 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic InRelease    
Hit:3 http://pr.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:4 http://pr.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]   
Hit:5 http://ppa.launchpad.net/webupd8team/haguichi/ubuntu bionic InRelease    
Get:7 http://pr.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB] 
Hit:6 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease  
Fetched 252 kB in 21s (11.7 kB/s)                               
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2.3~ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Requirement already up-to-date: gmusicapi in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: soundcloud in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: youtube-dl in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pafy in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pycountry in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: titlecase in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pychromecast in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: plexapi in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: fuzzywuzzy in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: eventlet in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: python-Levenshtein in /usr/lib/python2.7/dist-packages
Requirement already up-to-date: requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: gpsoauth>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: appdirs>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: protobuf>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: oauth2client>=1.1 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: mock>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: python-dateutil!=2.0,>=1.3 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: decorator>=3.3.1 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: validictory!=0.9.2,>=0.8.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: mutagen>=1.34 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: proboscis>=1.2.5.1 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: future in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: MechanicalSoup>=0.4.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from gmusicapi)
Requirement already up-to-date: fudge>=1.0.3 in /usr/local/lib/python2.7/dist-packages (from soundcloud)
Requirement already up-to-date: simplejson>=2.0 in /usr/local/lib/python2.7/dist-packages (from soundcloud)
Requirement already up-to-date: casttube>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from pychromecast)
Requirement already up-to-date: zeroconf>=0.17.7 in /usr/local/lib/python2.7/dist-packages (from pychromecast)
Requirement already up-to-date: websocket-client in /usr/local/lib/python2.7/dist-packages (from plexapi)
Requirement already up-to-date: tqdm in /usr/local/lib/python2.7/dist-packages (from plexapi)
Requirement already up-to-date: enum34; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from eventlet)
Requirement already up-to-date: monotonic>=1.4 in /usr/local/lib/python2.7/dist-packages (from eventlet)
Requirement already up-to-date: dnspython>=1.15.0 in /usr/local/lib/python2.7/dist-packages (from eventlet)
Requirement already up-to-date: greenlet>=0.3 in /usr/local/lib/python2.7/dist-packages (from eventlet)
Requirement already up-to-date: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
Requirement already up-to-date: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests!=1.2.0,!=2.12.0,!=2.12.1,!=2.12.2,!=2.18.2,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0->gmusicapi)
Requirement already up-to-date: pycryptodomex>=3.0 in /usr/local/lib/python2.7/dist-packages (from gpsoauth>=0.2.0->gmusicapi)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf>=3.0.0->gmusicapi)
Requirement already up-to-date: httplib2>=0.9.1 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi)
Requirement already up-to-date: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi)
Requirement already up-to-date: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=1.1->gmusicapi)
Requirement already up-to-date: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock>=0.7.0->gmusicapi)
Requirement already up-to-date: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock>=0.7.0->gmusicapi)
Requirement already up-to-date: lxml in /usr/local/lib/python2.7/dist-packages (from MechanicalSoup>=0.4.0->gmusicapi)
Requirement already up-to-date: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from MechanicalSoup>=0.4.0->gmusicapi)
Requirement already up-to-date: typing; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from zeroconf>=0.17.7->pychromecast)
Requirement already up-to-date: ifaddr in /usr/local/lib/python2.7/dist-packages (from zeroconf>=0.17.7->pychromecast)
Requirement already up-to-date: soupsieve>=1.2 in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4->MechanicalSoup>=0.4.0->gmusicapi)
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from ifaddr->zeroconf>=0.17.7->pychromecast)
Requirement already up-to-date: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve>=1.2->beautifulsoup4->MechanicalSoup>=0.4.0->gmusicapi)
Collecting git+https://github.com/plamere/spotipy.git
  Cloning https://github.com/plamere/spotipy.git to /tmp/pip-4oyWSk-build
Requirement already up-to-date: requests>=2.3.0 in /usr/local/lib/python2.7/dist-packages (from spotipy==2.4.4)
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from spotipy==2.4.4)
Requirement already up-to-date: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4)
Requirement already up-to-date: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.3.0->spotipy==2.4.4)
Installing collected packages: spotipy
  Found existing installation: spotipy 2.4.4
    Uninstalling spotipy-2.4.4:
      Successfully uninstalled spotipy-2.4.4
  Running setup.py install for spotipy ... done
Successfully installed spotipy-2.4.4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libspotify12 is already the newest version (12.1.51-1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tizonia-all
Oops. Something went wrong!
```

**Comment by siulynot** [comment] 2019-02-28 22:34
The weird thing is that is was working flawlessly for some months after i did the upgrade to ubuntu 18.04.

**Comment by juanrubio** [comment] 2019-03-01 10:03
I have installed a fresh Xubuntu 18.04.2 virtual machine and have installed Tizonia using the install script. After adding the Spotify credentials to tizonia.conf, Spotify worked for me without any problems.

So I believe that your upgrade from 16.04 to 18.04 did not go well the first time around. Tizonia would not be reporting those versions of Boost and TagLib otherwise. And that is potentially a problem since Tizonia's debian packages for Bionic have been built to run against those libraries that come with Bionic, not older (i..e we have Tizonia packages for Xenial, which provide binaries specifically built for Xenial).

> but i followed the command to purge tizonia and deleted the binaries from /usr/bin/

It is impossible for me to help you troubleshoot unless you provide exact details (e.g. what command did you run to purge tizonia, and why did you manually delete binaries from /usr/bin, that is never needed if you run the right apt-get commands).

**Comment by siulynot** [comment] 2019-03-05 12:05
The weird thing is that is was working flawlessly for some months after i did the upgrade to ubuntu 18.04. It was not only until now that it broke.

**Comment by siulynot** [comment] 2019-03-05 12:49
btw, i used this command to remove tizonia completely:

```sudo apt-get -y remove --purge tizonia-all && sudo apt-get -y autoremove```

**Comment by juanrubio** [comment] 2019-03-05 13:53
Ok, this is what I would do:

First, a good proper upgrade to your system. Then install Tizonia with the install script. All of that can be done with the following one-liner (note 'tizonia-install.log' being generated with the output, please upload here in case of issues).

Copy-paste into your terminal literally:
```
( sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt-get -y autoremove && sudo apt-get -y autoclean && cat /etc/apt/sources.list && curl -kL https://goo.gl/Vu8qGR | bash ) 2>1 | tee tizonia-install.log
```

Then remove your Spotify cache:
```
$ sudo rm -rf /var/tmp/tizonia-siu-spotify-129962567
```

Finally, run Tizonia to play some Spotify music.

**Comment by siulynot** [comment] 2019-03-05 14:35
[tizonia-install.log](https://github.com/tizonia/tizonia-openmax-il/files/2931354/tizonia-install.log)

**Comment by siulynot** [comment] 2019-03-05 14:44
I think i found the issue in sources.list:

```
#deb https://dl.bintray.com/tizonia/ubuntu bionic main # disabled on upgrade to bionic
```

**Comment by juanrubio** [comment] 2019-03-05 14:45
Correct:

```
# deb http://apt.mopidy.com/ stable main contrib non-free # disabled on upgrade to bionic
# deb https://dl.bintray.com/tizonia/ubuntu bionic main # disabled on upgrade to bionic
```
Please uncomment these two lines and try the installation script once more.

**Comment by siulynot** [comment] 2019-03-05 14:46
But now, even after removing spotify cache, i get this: 

```
izonia 0.17.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Spotify] [Connecting] : '129962567'.
[Spotify] [Album search] 'Wet Baes'.
[Spotify] [Album] 'Changes'.
[Spotify] [Track] 'Overture' [Wet Baes].
[Spotify] [Track] 'Changes' [Wet Baes].
[Spotify] [Track] 'Secret (Love Song)' [Wet Baes].
[Spotify] [Track] 'Is This Really Happening?' [Wet Baes].
[Spotify] [Track] 'Feels / Dancing in the Dark (Reprise)' [Wet Baes].
[Spotify] [Track] 'Guess' [Wet Baes].
[Spotify] [Track] 'Stay' [Wet Baes].
[Spotify] [Track] 'The End (Sitting in the Sun)' [Wet Baes].
[Spotify] [Tracks in queue] '8'.
[Spotify] [Cache]: '/var/tmp/tizonia-siu-spotify-129962567'

```
Stuck there.

**Comment by juanrubio** [comment] 2019-03-05 14:57
What is this giving you now?

```
$ tizonia --debug
```

Also, please export this variable, try again and upload the logs:
```
$ export TIZONIA_SPOTIFYPROXY_DEBUG=1
```

**Comment by siulynot** [comment] 2019-03-05 15:53
```
tizonia --debug
tizonia 0.17.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_65_1]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v17.12]

```

**Comment by siulynot** [comment] 2019-03-05 15:55
```
 tizonia --spotify-album "Wet Baes"
tizonia 0.17.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Spotify] [Connecting] : '129962567'.
[2019-03-05 11:54:17,360] [ INFO] [140058510022400] [tizspotifyproxy:enqueue_album:230] - arg : Wet Baes
[Spotify] [Album search] 'Wet Baes'.
[2019-03-05 11:54:17,363] [DEBUG] [140058510022400] [connectionpool:_new_conn:813] - Starting new HTTPS connection (1): accounts.spotify.com:443
[2019-03-05 11:54:22,853] [DEBUG] [140058510022400] [connectionpool:_make_request:393] - https://accounts.spotify.com:443 "POST /api/token HTTP/1.1" 200 None
[2019-03-05 11:54:22,856] [DEBUG] [140058510022400] [connectionpool:_new_conn:813] - Starting new HTTPS connection (1): api.spotify.com:443
[2019-03-05 11:54:28,425] [DEBUG] [140058510022400] [connectionpool:_make_request:393] - https://api.spotify.com:443 "GET /v1/search?q=Wet+Baes&type=album&limit=10&offset=0 HTTP/1.1" 200 None
[2019-03-05 11:54:28,429] [ INFO] [140058510022400] [tizspotifyproxy:__enqueue_album:819] - __enqueue_album
[Spotify] [Album] 'Changes'.
[2019-03-05 11:54:28,430] [DEBUG] [140058510022400] [connectionpool:_new_conn:813] - Starting new HTTPS connection (1): api.spotify.com:443
[2019-03-05 11:54:33,692] [DEBUG] [140058510022400] [connectionpool:_make_request:393] - https://api.spotify.com:443 "GET /v1/albums/6xdQSnEnqp5vdm9HOubcRB/tracks/?limit=50&offset=0 HTTP/1.1" 200 None
[2019-03-05 11:54:33,699] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,700] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'Overture' [Wet Baes].
[2019-03-05 11:54:33,700] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,700] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'Changes' [Wet Baes].
[2019-03-05 11:54:33,700] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,700] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'Secret (Love Song)' [Wet Baes].
[2019-03-05 11:54:33,700] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,701] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'Is This Really Happening?' [Wet Baes].
[2019-03-05 11:54:33,701] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,701] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'Feels / Dancing in the Dark (Reprise)' [Wet Baes].
[2019-03-05 11:54:33,701] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,701] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'Guess' [Wet Baes].
[2019-03-05 11:54:33,701] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,702] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'Stay' [Wet Baes].
[2019-03-05 11:54:33,702] [ INFO] [140058510022400] [tizspotifyproxy:__init__:130] - TrackInfo
[2019-03-05 11:54:33,702] [ INFO] [140058510022400] [tizspotifyproxy:__init__:141] - TrackInfo end
[Spotify] [Track] 'The End (Sitting in the Sun)' [Wet Baes].
[Spotify] [Tracks in queue] '8'.
[2019-03-05 11:54:33,702] [ INFO] [140058510022400] [tizspotifyproxy:next_uri:709] - 
[Spotify] [Cache]: '/var/tmp/tizonia-siu-spotify-129962567'
```

**Comment by juanrubio** [comment] 2019-03-05 16:23
Things are looking better. Let's continue:

Could you please create a file (`$HOME/.log4crc`) and add the following contents in it? Then please re-run and upload the log file that will be created: `/tmp/tizonia.log`

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE log4c SYSTEM "">

<log4c version="1.2.1">

	<config>
		<bufsize>0</bufsize>
		<debug level="2"/>
		<nocleanup>0</nocleanup>
		<reread>1</reread>
	</config>

        <category name="root" priority="trace" appender="tizlogfile" />

	<layout name="tiz" type="tiz_layout"/>
	<rollingpolicy name="tizrolling" type="sizewin" maxsize="10000000" maxnum="10" />
	<appender name="tizlogfile" type="rollingfile" logdir="/tmp" prefix="tizonia.log" layout="tiz" rollingpolicy="tizrolling" />
</log4c>
```

**Comment by juanrubio** [comment] 2019-03-05 16:23
Make sure you remove your Spotify password from the uploaded file.

**Comment by siulynot** [comment] 2019-03-05 17:24
[tizonia.log](https://github.com/tizonia/tizonia-openmax-il/files/2932017/tizonia.log)

**Comment by siulynot** [comment] 2019-03-11 17:29
Finally found the problem. I feel a bit of shame... seems like the VPN service i was using was interfering in the music stream. :/

**Comment by tizonia** [comment] 2019-03-11 20:26
No worries, I'm glad you found the root cause.

Thanks for reporting! (I'm closing the issue now).

**Closed by tizonia** 2019-03-11 20:26 UTC
