### ISSUE TITLE
Can't find a supported Debian or Ubuntu-based distribution.

### ISSUE THREAD

**Issue by orschiro** [tizonia/tizonia-openmax-il#304] opened 2017-03-16 18:16 UTC
Dear all, 

I just used the command `curl -kL https://goo.gl/Vu8qGR | bash` on Ubuntu 16.10 and get the following error:

```
orschiro@x230:~$ curl -kL https://goo.gl/Vu8qGR | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   255    0   255    0     0    449      0 --:--:-- --:--:-- --:--:--   450
100   150  100   150    0     0     96      0  0:00:01  0:00:01 --:--:--   156
100  3752  100  3752    0     0   1654      0  0:00:02  0:00:02 --:--:--  5493
Can't find a supported Debian or Ubuntu-based distribution.
```

Any advice?

Yours,

Robert

**Comment by juanrubio** [comment] 2017-03-16 22:45
Hi Robert,

Sorry about that, unfortunately this is 'expected behaviour': there are no binaries for Ubuntu 16.10. 

The reason why I didn't produce them for 16.10 is very simple; it takes a bit of time to package Tizonia for every distro, and 16.10 (and all "Ubuntu dot-ten" releases for that matter) is simply not worth my time. Ubuntu only support Dot-ten releases for six months, and in addition to that, at least in my experience, they tend to be very 'beta-quality', as Ubuntu is always trying something new before they get it officially unveiled in the much more polished Dot-O-Fours.

In the future, I would like to produce docker images and snaps, but for now only debs hosted on Bintray, for a bunch of long-term supported Debian/Ubuntu distros (see README.md). I will consider creating Binaries for 17.04, but I would not hold my breath on it.

**Comment by orschiro** [comment] 2017-03-17 08:09
Thank you, Juan!

I appreciate your response and understand your reasoning.

Let me ask: is there any simple way I can install tizonia on Ubuntu 16.10
then?

Yours,

Robert

**Comment by juanrubio** [comment] 2017-03-17 18:23
Hey Robert,

There is definitely a way, but I'm not sure if it is a 'simple' way :-)

You can always try to build Tizonia from source. Try this and let me know if it works for you:
```
# Install git, if not yet installed
sudo apt-get install git

# Clone tizonia
git clone https://github.com/tizonia/tizonia-openmax-il
cd tizonia-openmax-il

# Export some environment variables
export TIZONIA_REPO_DIR=/path.to.tizonia.repo # (e.g. /home/robert/tizonia-openmax-il)
export TIZONIA_INSTALL_DIR=/usr
export PATH=$TIZONIA_REPO_DIR/tools:$PATH

# Install Tizonia's dependencies
$ tools/tizonia-dev-build --deps

# Configure, build, and install a single 'deb' package in one go
tools/tizonia-dev-build --debian

# While you wait.. go grab a coffee... and maybe some dinner too...

# If everything went well... copy the config file to you home config folder, and add your credentials there
$ mkdir -p $HOME/.config/tizonia
$ cp $TIZONIA_REPO_DIR/config/src/tizonia.conf $HOME/.config/tizonia
```

A little disclaimer: these build instructions usually render a single deb package that gets installed on your system and provides a functional Tizonia installation, useful for testing purposes. I've tested it successfully on other distros, but your milage in Ubuntu 16.10 may vary.

Let me know how it goes!

**Comment by orschiro** [comment] 2017-03-17 18:39
Dear Juan,

I am very grateful for your detailed instructions!

I hope they will be useful for other users as well.

For now, however, I am not going to take the time to try it.

I might do it later though!

Yours,

Robert

**Comment by juanrubio** [comment] 2017-03-17 19:45
No problem Robert. 

I've just managed to test it on a 16.10 vm and the recipe seems to work fine there too.
So I'm closing this for now. Feel free to comment or reopen if you need any help.

**Closed by juanrubio** 2017-03-17 19:45 UTC

**Comment by orschiro** [comment] 2017-03-17 19:46
I appreciate your efforts!

Yours,

Robert
