### ISSUE TITLE
Spotify: config option to allow/disallow 'explicit' tracks

### ISSUE THREAD

**Issue by juanrubio** [tizonia/tizonia-openmax-il#568] opened 2019-03-03 21:01 UTC
The goal is to have a configuration file option and command-line flag to allow-disallow explit songs.

**Comment by tizonia** [comment] 2019-03-13 22:12
Changes are in the develop branch. Will be merged to master soon.

**Closed** 2019-03-13 22:31 UTC
Labels: enhancement

**Comment by WhiskeyTuesday** [comment] 2019-09-01 01:07
Tizonia 0.18.0 installed via apt on Ubuntu 18.04 has this option in its default config file but changing it to true doesn't seem to actually do anything. calling `tizonia --spotify-playlist` on a playlist with explicit tracks still gives 'explicit tracks removed'. calling with `--spotify-allow-explicit-tracks` does work as intended however.

**Comment by ROF618** [comment] 2020-01-19 02:28
Having the same problem as @WhiskeyTuesday. I also am running Ubuntu 18.04 lts and my Tizonia is version 0.19.0.

**Comment by WhiskeyTuesday** [comment] 2020-01-19 12:28
@ROF618 `spotify.allow_explicit_tracks = true` in the config file works on my current install which is 0.18.0 installed with snapd on Pop_OS (Ubuntu) 19.10. I can't remember if it just started working when I switched to the snap installed version, or when I switched to 19.10... or... I vaguely remember the default version of the line in the config file is commented out but doesn't include '= true' maybe?

I've clearly forgotten everything but hopefully this is helpful in some way.

**Comment by tizonia** [comment] 2020-01-19 20:33
@WhiskeyTuesday , @ROF618 

Apologies, this fell through the cracks. Yes, the config option works for me as well.

The config parser is not very good (maybe that's even an overstatement!), so you need to make sure your config lines look clean like this (no comment symbols '#' before or after, etc).

```
spotify.allow_explicit_tracks = false
```

**Comment by WhiskeyTuesday** [comment] 2020-01-20 16:43
@tizonia now that you mention it I think that's what fixed it. I think I originally had an inline comment after the option, on the same line.

**Comment by tizonia** [comment] 2020-01-20 17:17
@WhiskeyTuesday 

The fix for this particular problem (options ignored if comment at the end of the line) is now available in the 'develop' branch.

See #667
