### ISSUE TITLE
Fast Forward and rewind

### ISSUE THREAD

**Issue by metalerk** [tizonia/tizonia-openmax-il#608] opened 2019-07-03 04:03 UTC
# Fast Forward and rewind

### Description

Not sure but I can't find a way to fast forward or rewind to listen a specific part of the song.
Is this feature currently available?

### Versions

Tizonia 0.18.0
Debian 9

**Comment by tizonia** [comment] 2019-07-04 11:53
Hi!, and thanks for taking the time to open an issue. This is always appreciated!

Yes, unfortunately, we don't have seek functionality implemented in Tizonia. This is tracked by #438. 
Please, read through that issue and comment there if you need to.

I am closing this one as a duplicate of #438

**Closed by tizonia** 2019-07-04 11:53 UTC
Labels: duplicate
