### ISSUE TITLE
spotify: unable to play some playlists

### ISSUE THREAD

**Issue by herohamp** [tizonia/tizonia-openmax-il#471] opened 2018-03-26 23:49 UTC
### Description

I am trying to play a spotify playlist I followed

### Steps to Reproduce

1. tizonia --spotify-playlist "Chill Hits"  

**Expected behavior:** Play the playlist

**Actual behaviour:** Plays a random playlist

**Reproduces how often:** 100% I have never gotten it to play the followed playlist

### Versions

tizonia 0.11.0. Copyright (C) 2017 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>
Debug Info:
	    * [Boost 1_66]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v17.12]
NAME="Anarchy Linux"
PRETTY_NAME="Anarchy Linux"
ID=anarchy
ID_LIKE=anarchylinux
ANSI_COLOR="0;36"
HOME_URL="https://anarchy-linux.org/"

### Installation Method Used

Pacaur iirc

**Comment by tizonia** [comment] 2018-03-27 08:52
Hi!, thanks for taking the time to report this issue.

Yes, this is a genuine problem. It occurs with some of my playlists as well. I don't know why this is happening. I always attributed to my poor understanding of libspotify, which is used by tizonia's Spotify plugin. The issue is that I decided not to invest a lot of time in libspotify because it has been officially deprecated by Spotify some time ago (see #395).

I think the best solution here is to ditch the existing [spotify_source OMX component](https://github.com/tizonia/tizonia-openmax-il/tree/master/plugins/spotify_source) and add a spotify role in the [http_source component](https://github.com/tizonia/tizonia-openmax-il/tree/master/plugins/http_source). For that Spotify role, [pyspotify](https://github.com/mopidy/pyspotify) sounds like the only option available right now. It also uses libspotify but probably it has this problem resolved plus it would allow tizonia to do spotify searches of other things than just playlists.

**Comment by juanrubio** [comment] 2018-05-10 10:17
Just as a note, libspotify does not seem to allow Spotify-made playlists to be played like it does with the playlists created by the user. I have not verified this with pyspotify, but I believe this is a shortcoming in the underlying (and unmaintained) libspotify.

**Comment by tizonia** [comment] 2018-06-15 17:09
Closing this now. Spotify Web API functionality has now been merged to master.

**Closed by tizonia** 2018-06-15 17:09 UTC
Labels: bug, enhancement, help wanted
