### ISSUE TITLE
Tizonia seems to be ignoring proxy

### ISSUE THREAD

**Issue by fabianvdmeer** [tizonia/tizonia-openmax-il#722] opened 2020-04-28 14:47 UTC
I have been trying to setup Tizonia on my lubuntu system, it all works fine except I can't seem to get a proxy working. I edit the config file at the line proxy_server line and when I start spotify everything seems to work. But to test if it works I decided to fill in random ip's and numbers and spotify still connects and starts playing like everything is fine. Does this mean proxies are ignored by Tizonia? Or how should I interpret this? And is there a way to get proxies to work? Love the program btw!

**Comment by tizonia** [comment] 2020-04-28 16:39
Hi @fabianvdmeer 

Thanks for taking the time to report an issue.

Yes, there is currently a problem with the use of proxy for Spotify in Tizonia. 

Please see issue #626

**Comment by tizonia** [comment] 2020-04-28 16:40
Closing as duplicate of #626

**Closed by tizonia** 2020-04-28 16:40 UTC
