### ISSUE TITLE
Can't install Tizonia on ARMHF hardware

### ISSUE THREAD

**Issue by TartanSpartan** [tizonia/tizonia-openmax-il#594] opened 2019-05-12 09:14 UTC
[Description of the issue]

I can't install the program because thee dependencies python-tizplexproxy, python-tizchromecastproxy and python-tizspotifyproxy don't appear to be built for ARMHF hardwware.

**Expected behavior:**

These dependencies should install.

**Actual behaviour:**

They are not available, so don't.

**Reproduces how often:** 

100%

### Versions

0.18.0 for Ubuntu Touch 16.04.

### Installation Method Used

Bintray debs.

### Additional Information

I suppose I'll have to build these dependencies myself unless the developers have any other suggestions?

**Comment by tizonia** [comment] 2019-05-12 09:58
Hi!, thanks for trying the software and taking the time to report an issue.

Honestly, I'm not sure what's going on other than a hiccup of some sort. Looking in the Bintray package list, it looks like everything is correct and the packages are there: 

See in : https://bintray.com/tizonia/ubuntu/tizonia-xenial/0.18.0#files/pool%2Fmain%2Ft%2Ftizonia-xenial

![image](https://user-images.githubusercontent.com/3161606/57580670-09a75100-74df-11e9-8f9f-391969bd8a71.png)

Perhaps you could run the installer once more and see if those packages are retrieved this time. Or maybe you can manually download the missing debs and get them installed to see if everything works?

**Comment by TartanSpartan** [comment] 2019-05-12 12:51
phablet@ubuntu-phablet:~$ libertine-container-manager exec -i xervus -c "apt install tizonia-all"
Reading package lists... Done                                                         
Building dependency tree                                                              
Reading state information... Done                                                     
Some packages could not be installed. This may mean that you have                     
requested an impossible situation or if you are using the unstable                    
distribution that some required packages have not yet been created                    
or been moved out of Incoming.                                                        
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tizonia-all : Depends: python-tizplexproxy but it is not installable
               Depends: python-tizchromecastproxy but it is not installable
               Depends: python-tizspotifyproxy but it is not installable
E: Unable to correct problems, you have held broken packages.

I then tried to download one of the packages and install it manually, like you suggested, but:

phablet@ubuntu-phablet:~$ libertine-container-manager exec -i xervus -c "dpkg -i python-tizspotifyproxy_0.18.0-1_arm.deb"
dpkg: error processing archive python-tizspotifyproxy_0.18.0-1_arm.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 python-tizspotifyproxy_0.18.0-1_arm.deb

**Comment by TartanSpartan** [comment] 2019-05-13 11:31
@tizonia It appears that there is commonality between this issue and https://github.com/tizonia/tizonia-openmax-il/issues/553. I note that both Ubuntu Touch and Raspberry Pi run on ARM hardware. Is it possible for you to package python-tizspotifyproxy_0.18.0-1_all.deb and the other two dependencies purely as an armhf.deb file? I have no trouble installing those on my devices.

**Comment by tizonia** [comment] 2019-05-19 09:11
@TartanSpartan , sorry for the delayed reply.

I don't think #553 is related, although they look similar because I think the root cause is probably of the same nature. What I mean by that is that I believe your system has some broken packages and that is what is preventing the installation of some of Tizonia's packages:

```
The following packages have unmet dependencies:
tizonia-all : Depends: python-tizplexproxy but it is not installable
Depends: python-tizchromecastproxy but it is not installable
Depends: python-tizspotifyproxy but it is not installable
E: Unable to correct problems, you have held broken packages.
```

See here, it may be helpful:
https://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages

I believe you need to correct the problem by either forcing the installation of the broken packages or by removing them from your system. That might unblock the installation of the Tizonia packages (hopefully!).

Let me know how it goes.

**Comment by tizonia** [comment] 2019-12-13 13:31
Closing this issue for now. Please reopen if you find evidence of an issue in Tizonia.

**Closed by tizonia** 2019-12-13 13:31 UTC
