### ISSUE TITLE
Plex audio cuts out after 18 seconds on Arch distro

### ISSUE THREAD

**Issue by jpwhale** [tizonia/tizonia-openmax-il#679] opened 2020-02-08 15:35 UTC
While playing a Plex album the audio cuts out abruptly after a short while, more specifically after app. 17-18 seconds. I have no idea if this is a timeout issue, or buffer issue, or PCM issue or whatever.

Any ideas how to identify the problem, or what configuration is needed to test/fix this?

```
tizonia 0.19.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
	    * [Boost 1_72]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v19.09]
```

Installed from Arch AUR

**Comment by tizonia** [comment] 2020-02-09 19:36
Hi!, thanks for taking the time to report an issue.

I've just done some testing. My Plex server is at version 1.18.5.2309 and I can't see any audio cuts. It works fine for me.

Are you using this version, or something older?

**Comment by jpwhale** [comment] 2020-02-09 19:43
Thank you for your time!

I'm using plex 1.18.6.2368.

I have a sneaky feeling it's a problem on my machine. I get a weird volume indicator dbus message when it happens. I'm just not tech savvy enough to figure out why.

Do you know if using the plex API like this requires plex pass? I do have that, and I have updated the token after getting it, but I wondered if it might be related.

**Comment by tizonia** [comment] 2020-02-09 20:23
> Do you know if using the plex API like this requires plex pass? I do have that, and I have updated the token after getting it, but I wondered if it might be related.

The plex pass is not required to use the API. 

I've got a Manjaro VM. I'll try to test with it when I have some time and report back.

**Comment by nettosama** [comment] 2020-02-18 06:20
Same thing happens to me. Also using Arch, installed from AUR, and same debug info. It mutes after 18-20 seconds. Progress bar keeps going, but no audio.

**Comment by tizonia** [comment] 2020-02-18 09:22
Hi @jpwhale / @nettosama 

I've been able to reproduce it on my Manjaro VM. I can't reproduce it on Ubuntu.

Apparently, the audio buffer used by Tizonia while streaming from Plex on Manjaro is not enough for some strange reason (however, it is sufficient on Ubuntu).

On my Manjaro tests, I am able to avoid the cuts by changing the default buffer value from 60 seconds to 600 seconds. This is the only value I have tested. It might get fixed with something smaller than 600.
https://github.com/tizonia/tizonia-openmax-il/blob/eed901e408ffcb9ab2527ce37670fcf4bd0439fe/config/src/tizonia.conf.in#L161

I'll keep this issue open for now to investigate some more.

**Comment by nettosama** [comment] 2020-02-19 01:14
Posting here again, changing the buffer value to 600 indeed made it play the song past the 18 seconds, and I it played correctly several songs, but it stopped again at the 4th song, each song being around 4:30 mins. It happened twice, when playing a playlist.

**Comment by tizonia** [comment] 2020-02-19 08:55
Hi @nettosama 

Thanks for trying this. I'll reopen, there must be some other problem in there that seems to be only reproducible with the Arch/Manjaro dependencies.

**Comment by tizonia** [comment] 2020-03-04 21:44
Hi @jpwhale / @nettosama

Just a little update. I've got a fix that's looking promising. Hopefully, I'll get it in a new release very soon.

**Closed** 2020-03-08 20:42 UTC
Labels: bug
