### ISSUE TITLE
tools/install.sh still does not work for ubuntu-16.04

### ISSUE THREAD

**Issue by inecho** [tizonia/tizonia-openmax-il#373] opened 2017-10-07 20:05 UTC
.. the installer has problems with the following packages:
`The following packages are UNAUTHENTICATED: libtizaacdec0 libtizcore-dev libtizcore0 libtizonia-dev libtizplatform-dev libtizrmproxy-dev tizilheaders tizrmd tizrmd-dev Requires the installation of the following packages: check libdbus-c++-bin libdbus-c++-dev libev-dev libev4 liblog4c-dev libsubunit-dev libsubunit0 libtizaacdec0 libtizcore-dev libtizcore0 libtizonia-dev libtizplatform-dev libtizrmproxy-dev tizilheaders tizrmd tizrmd-dev `

**Comment by juanrubio** [comment] 2017-10-08 08:35
uh..that's embarrassing :-( ... I'll have a look to see what's going on...

**Comment by juanrubio** [comment] 2017-10-08 21:08
All right, I think the problem is fixed now. The repository signing failed when I uploaded the binaries to Bintray the last time and I did not notice. This has been sorted.

You can re-download and re-run the install.sh script in the usual way, but before doing that, make sure you remove this line from /etc/apt/sources.list

e.g.: (use any editor you like, with sudo)

sudo nano /etc/apt/sources.list

```
deb https://dl.bintray.com/tizonia/raspbian stretch main
```

**Comment by inecho** [comment] 2017-10-13 16:58
thanks for the quick response, it works great!

**Closed** 2017-10-13 16:57 UTC

**Comment by juanrubio** [comment] 2017-10-16 09:30
Great!, thanks for your feedback.
