### ISSUE TITLE
API enchancement

### ISSUE THREAD

**Issue by ebanDev** [tizonia/tizonia-openmax-il#712] opened 2020-04-13 16:56 UTC
Hello, I'm reopening an issue because I had an idea that could be (I think 😁) really interesting.  
I think we could make an API to be able to interact with Tizonia from a mobile app / website.  
We could make, for example, a GET request like 

> `192.168.1.14:8765/?command="pause"`

Or something like that!  
I would really love to see this feature coming!

**Comment by juanrubio** [comment] 2020-04-13 21:50
Hi!,

Actually, the idea has been proposed several times in the past, in different ways.

See the 'RPC interface / headless support' item in the [ROADMAP](https://github.com/tizonia/tizonia-openmax-il/blob/master/ROADMAP.md).

Also, bugs #488, #509, #551 have more context.

Finally, there is also DBUS-based MPRISv2 interface that is functional (with certain limitations) and may be used to control Tizonia from another terminal or application running on the same machine:
https://docs.tizonia.org/manual/mprisv2.html

**Comment by tizonia** [comment] 2020-04-13 21:52
@ebanDev 

Thanks!, I'm closing this issue as a duplicate of  #488, #509, #551

**Closed by tizonia** 2020-04-13 21:52 UTC

**Comment by ebanDev** [comment] 2020-04-13 22:44
Okay! Thank you very much for your response.

**Comment by ebanDev** [comment] 2020-04-14 08:32
Hi, I just wanted to ask you, when are you planning to implement the metadata function?
Thanks again for your great project!
